"""Add role_id to users table

Revision ID: e0d7d32125c1
Revises: 34fbca5b5f15
Create Date: 2025-08-16 03:15:25.003242

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e0d7d32125c1"
down_revision: Union[str, None] = "34fbca5b5f15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
